version: '2'
services:
  jhipsterreactjsstore-app:
    image: jhipsterreactjsstore
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterreactjsstore-postgresql:5432/jhipsterReactjsStore
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 80110:80110
  jhipsterreactjsstore-postgresql:
    extends:
      file: postgresql.yml
      service: jhipsterreactjsstore-postgresql
